package MemorIA.service;

import MemorIA.dto.AlertDTO;
import MemorIA.entity.Patient;
import MemorIA.entity.alerts.Alert;
import MemorIA.repository.AlertRepository;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.Collections;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
@Slf4j
public class AlertService {

    private final AlertRepository alertRepository;
    private final IPlanningService planningService;

    public List<AlertDTO> getAlertsForCurrentUser(Long userId, String role) {
        log.info("[AlertService] Getting alerts for user {} with role {}", userId, role);
        return Collections.emptyList();
    }

    public List<AlertDTO> getAlertsForPatient(Long patientId) {
        log.info("[AlertService] Getting alerts for patient {}", patientId);
        List<Alert> alerts = alertRepository.findByPatientIdOrderByCreatedAtDesc(patientId);
        return alerts.stream()
                .map(this::toAlertDTO)
                .collect(Collectors.toList());
    }

    public List<AlertDTO> getAllAlertsForDoctor(Long doctorId) {
        log.info("[AlertService] Getting all alerts for doctor {}", doctorId);
        try {
            // Récupérer tous les patients du docteur
            List<Patient> patients = planningService.getDoctorPatients(doctorId);
            
            if (patients == null || patients.isEmpty()) {
                log.info("[AlertService] No patients found for doctor {}", doctorId);
                return Collections.emptyList();
            }
            
            // Extraire les IDs des patients
            List<Long> patientIds = patients.stream()
                    .map(Patient::getId)
                    .collect(Collectors.toList());
            
            // Récupérer les alertes pour tous ces patients
            List<Alert> alerts = alertRepository.findByPatientIdInOrderByCreatedAtDesc(patientIds);
            
            // Convertir en DTOs
            return alerts.stream()
                    .map(this::toAlertDTO)
                    .collect(Collectors.toList());
        } catch (Exception e) {
            log.error("[AlertService] Error loading alerts for doctor {}: {}", doctorId, e.getMessage(), e);
            return Collections.emptyList();
        }
    }

    public AlertDTO getAlertById(Long alertId) {
        log.info("[AlertService] Getting alert {}", alertId);
        throw new RuntimeException("Alert not found: " + alertId);
    }

    private AlertDTO toAlertDTO(Alert alert) {
        String patientName = alert.getPatient() != null && alert.getPatient().getUser() != null
                ? alert.getPatient().getUser().getPrenom() + " " + alert.getPatient().getUser().getNom()
                : "Unknown";
        
        String createdByName = alert.getCreatedBy() != null
                ? alert.getCreatedBy().getPrenom() + " " + alert.getCreatedBy().getNom()
                : null;
        
        String assignedToUserName = alert.getAssignedToUser() != null
                ? alert.getAssignedToUser().getPrenom() + " " + alert.getAssignedToUser().getNom()
                : null;
        
        String resolvedByUserName = alert.getResolvedByUser() != null
                ? alert.getResolvedByUser().getPrenom() + " " + alert.getResolvedByUser().getNom()
                : null;
        
        return new AlertDTO(
                alert.getId(),
                alert.getPatient().getId(),
                patientName,
                alert.getTitle(),
                alert.getDescription(),
                alert.getType(),
                alert.getStatus(),
                alert.getSeverity(),
                alert.getCreatedAt(),
                alert.getUpdatedAt(),
                alert.getAssignedAt(),
                alert.getResolvedAt(),
                alert.isRead(),
                alert.getCreatedBy() != null ? alert.getCreatedBy().getId() : null,
                createdByName,
                alert.getAssignedToUser() != null ? alert.getAssignedToUser().getId() : null,
                assignedToUserName,
                alert.getResolvedByUser() != null ? alert.getResolvedByUser().getId() : null,
                resolvedByUserName,
                alert.getReminderId(),
                alert.isAutoGenerated(),
                alert.getGravityScore(),
                null,  // gravityExplanation - not available in Alert entity
                null,  // color - not available in Alert entity
                alert.isCritical(),
                alert.getClinicalNote()
        );
    }
}
